// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGETOUR.API.Infrastructure.Data;

#nullable disable

namespace SIGETOUR.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923052929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGETOUR.API.Core.Entities.TourImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TourPackageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TourPackageId");

                    b.ToTable("TourImages");
                });

            modelBuilder.Entity("SIGETOUR.API.Core.Entities.TourPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Inclusions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("TourPackages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BasePrice = 0m,
                            Description = "Ventanillas de Otuzco (Cementerio de la Cultura Cajamarca con más de 3 mil años de antigüedad), Jardín de las Hortensias, Artesanía de Cajamarca, Fundo los Aples o 'Tres Molinos', fábrica artesanal de quesos, mantequilla, manjar blanco, Rosquitas de manteca etc.",
                            Inclusions = "Movilidad + Guía de turismo",
                            IsActive = true,
                            Schedule = "3:30pm – 6:30pm",
                            Subtitle = "Cementerio pre-inca",
                            Title = "Ventanillas de Otuzco"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BasePrice = 0m,
                            Description = "Ex - hacienda La Collpa, Laguna Artificial, Casa Hacienda, Capilla de la Virgen del Carmen, Establo Central, Llamado de Vacas por su nombre, degustación de Lácteos; visita a las Cascadas de Llacanora según temporada o talleres de cerámica utilitaria y decorativa.",
                            Inclusions = "Movilidad + Guía de turismo",
                            IsActive = true,
                            Schedule = "3:30pm – 7pm",
                            Subtitle = "Llamado de Vacas por su nombre",
                            Title = "Collpa"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BasePrice = 0m,
                            Description = "El Castillo de Yanamarca es un moderno atractivo turístico con arquitectura estilo medieval en donde se puede apreciar, pinturas, esculturas de piedra y madera. Este lugar ofrece vistas panorámicas espectaculares del valle circundante y cuenta con un restaurante moderno, cafetería, áreas de juegos y espacios temáticos.",
                            Inclusions = "Movilidad + Guía de turismo",
                            IsActive = true,
                            Schedule = "Horario a coordinar - Am o Pm",
                            Subtitle = "Estilo medieval",
                            Title = "Castillo de Yanamarca"
                        });
                });

            modelBuilder.Entity("SIGETOUR.API.Core.Entities.TourImage", b =>
                {
                    b.HasOne("SIGETOUR.API.Core.Entities.TourPackage", "TourPackage")
                        .WithMany("Images")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourPackage");
                });

            modelBuilder.Entity("SIGETOUR.API.Core.Entities.TourPackage", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
